### PR TITLE
Add Oculus browser hands support

### PR DESCRIPTION
**Pull request by cabanier**

### CODE REVIEW

**Comment by cabanier** [comment]
Closes #41

**Comment by AdaRoseCannon** [comment]
Thank you!!

**Comment by cabanier** [comment]
@AdaRoseCannon I think Layers is listed for Hololens but that should be hands I think.

**Comment by AdaRoseCannon** [comment]
Thanks for pointing it out! @Yonet can you confirm?

**Comment by Yonet** [comment]
@AdaRoseCannon yes, @cabanier is right.

**Pull request merged**
