### PR TITLE
Add information on Pico Browser

### PR DESCRIPTION
**Pull request by msub2**
Since I own a Pico 4 I figured I'd add some basic information on the browser's WebXR capabilities. Unfortunately I don't have exact version numbers when support was added (this information is not publicly available/was not publicly announced anywhere that I can find) so I've just filled it in as "Supported", which hopefully someone from PICO can expand on in the future.

### CODE REVIEW

**Comment by msub2** [comment]
@AdaRoseCannon

**Comment by AdaRoseCannon** [comment]
Sorry for the slow reply I just saw this, Correct me if I Am wrong but I think the Pico browser is Wolvic.

**Comment by msub2** [comment]
Older Pico headsets used Firefox Reality, but Pico Neo 3 and onwards use a bespoke Chromium fork as the default browser now.

**Comment by AdaRoseCannon** [comment]
Oh neat! Always makes me happy to see new browsers pop up.On 10 Mar 2023, at 18:14, Daniel Adams ***@***.***> wrote:﻿
Older Pico headsets used Firefox Reality, but Pico Neo 3 and onwards use a bespoke Chromium fork as the default browser now.

**Comment by AdaRoseCannon** [comment]
Thanks for rebasing!

**Pull request merged**
