### PR TITLE
Added a page describing Chrome's hardware support and related flags

### PR DESCRIPTION
**Pull request by toji**
I've gotten several questions regarding Chrome's hardware support and how to enable various headsets that aren't turned on by default. This page seems like an appropriate place to host that information.

Happy to address any concerns about formatting or the way the content is presented, just taking a stab at what feels congruous with the main page here.

(Semi-related question: How do you properly test the page locally? I'm not sure what's handling the embedded logic.)

### CODE REVIEW

**Comment by deirdremt** [comment]
Hi, I'm working with Nell over at Sumerian...do we have any idea when the other reviewer (Ada?) will be able to respond? Thanks!

**Comment by AdaRoseCannon** [comment]
So sorry i totally missed this PR thanks for nudging me. I'll do it now.

**Comment by AdaRoseCannon** [comment]
lgtm merging :)

**Comment by deirdremt** [comment]
wonderful, thank you!

**Pull request merged**
