### PR TITLE
Add Needle Engine

### PR DESCRIPTION
**Pull request by marwie**
Added needle engine tab + two showcase projects

### CODE REVIEW

**Comment by AdaRoseCannon** [comment]
Could you add more to the getting started page? With links to install the plugins and such. Enough so someone could follow the instructions and have a WebXR experience.

Also perhaps pick a single WebXR experience to add to the showcase, I really like the castle builder, but either is fine.

**Comment by marwie** [comment]
Hi @AdaRoseCannon added more info and removed the bike configurator

**Comment by AdaRoseCannon** [comment]
Thanks, could you `git rm` the bike image too?

**Comment by marwie** [comment]
No problem. I squashed it into one commit.
Let me know if you want me to change anything else

**Comment by AdaRoseCannon** [comment]
It's all good, merging now, I was just AFK

**Comment by marwie** [comment]
Thanks a lot! 🙏 😊 

I'll have to make another PR in a minute to fix the css (the image is overflowing - sorry didnt check that before)

**Pull request merged**
