### PR TITLE
Add Verge3D framework to Getting Started

### PR DESCRIPTION
**Pull request by alexkowel**
Verge3D is an easy-to-use WebGL/WebVR/WebXR framework with strong Blender, Max and Maya integration.

### CODE REVIEW

**Comment by AdaRoseCannon** [comment]
This is great, I hadn't heard of Verge3D before. Would you be able to add some more information to the guide e.g. instructions in for one of the editors such as Blender?

**Comment by alexkowel** [comment]
> This is great, I hadn't heard of Verge3D before. Would you be able to add some more information to the guide e.g. instructions in for one of the editors such as Blender?

Sure! We have a short AR/VR [guide](https://www.soft8soft.com/docs/manual/en/introduction/AR-VR-development.html). I can extract the most essential parts and convert to Markdown but it will require some images to be inlined. Should I add them as links to our website or push inside the **getting-started** directory?

Thanks!

**Comment by AdaRoseCannon** [comment]
Either is fine, whichever you prefer.

**Comment by alexkowel** [comment]
Done! Feel free to suggest any modifications to that guide.

**Pull request merged**
