### PR TITLE
initial threejs example

### PR DESCRIPTION
**Pull request by joshmarinacci**
added a full threejs example

### CODE REVIEW

**Comment by AdaRoseCannon** [comment]
This is really great! is it possible, to include how one could optionally support AR?

i.e.
```
        //add a button to enter/exit vr to the page,
        //use ARButton instead for AR
        document.body.appendChild(VRButton.createButton(renderer));
```

**Comment by AdaRoseCannon** [comment]
I'm just gonna merge for now :)

**Comment by joshmarinacci** [comment]
Sorry, I got caught up in other stuff.

I did a test and you can't have VRButton and ARButton on at the same time because they will overlap. Instead the comment could be something like this:

```
//add a button to enter/exit immersive mode
 document.body.appendChild(VRButton.createButton(renderer));

//For AR import ARButton at the top
//    import { ARButton } from 'https://unpkg.com/three/examples/jsm/webxr/ARButton.js';
// then create the button
//  document.body.appendChild(ARButton.createButton(renderer));
```

Look good?

**Comment by AdaRoseCannon** [comment]
That looks perfect!!

**Pull request merged**
